* Project ideas
** Assessment of the stability and activity of single atom catalysis
There have not been too many computational studies on this point. One of the few ones I could find was one that studied Fe adsorption on phosphine cite:kulish-2015-adsor, but there aren't that many results and the analysis isn't too strong. I wonder if many computationalists are not as interested in this. I guess supported nanoclusters have been studied in a while. Also the excitement for this single atom catalysis could be dwindling.

** Thermodynamic models for predicting surface segregation of mixed oxides
*** DONE Should probably read this article cite:richter-2013-concen-vacan.
** Project with organic perovskites for solar cell applications -- possibly an interface study
** Trends in reactivity of other inorganic compounds (nitrides, carbides, phosphides, sulfides)

A recent experimental paper from Jaramillo cite:kibsgaard-2014-molyb-phosp showed a mixed Sulfide/Phosphide was active for hydrogen evolution.

It seems like a majority of these deviations are done on very high surface-energy facts with many broken bonds. Higher quality work would take into account these considerations cite:michalsky-2014-depar-adsor.

** Understanding coverage effects on transition metal compounds

Results from Michalsky cite:michalsky-2014-depar-adsor also show a coverage effect for transition metal carbides with coadsorbed oxygen atoms. These are more apparent on reduced surfaces. I wonder if coverage is meaningful to investigate. I should look at a previous study of coverage

From their results of Scheffler cite:reuter-2003-compos-co,reuter-2004-stead-state, the only lower coverages they performed were at 0.125 and 0.25 ML coverage of rutile sites. With these calculations, they found less than a 0.15 eV difference in adsorption energies of O or CO. 

However, Rossmeisl has found up to a 1-2 eV effect of coverage on O and OH on both RuO2 and IrO2 cite:rossmeisl-2007-elect. Another paper found 3 eV level changes of the adsorption energy of Fe with coverage cite:pabisiak-2014-fe-fe2o3.

Similarly for perovskite surfaces, coverage plays an important role as well, wich up to 1.5 eV shifts in the adsorption energy cite:montoya-2015-theor.
** Correlations between adsorption on the same system but on geometrically different sites
** Understanding adsorption on mixed oxides through counting their correlations
cite:guo-2013-effec

* CMU
** <2015-05-15 Fri>
*** Industrial Career Seminar notes
**** Dr. Suzie Laurich- McIntyre talk
- Make sure to go to conferences (1st point)
- Get connected with the CMU alumni network
- Large emphasis on networking with EVERYBODY
- Getting involved in local/national professional organization
- Ask John for more professional responsibilities
- Have at least 5 different elevator talks
  - Will depend on the sort of company you want to work for
  - From least dumb-down to most technical
  - Make sure you know the "why" of you're studying
- Career and development center to find out where students have gone
- Check old career fair conferences for people hiring 
- Think about ways to build my CV
- Have a unique CV for each company
- Cover letter notes
  - Who you've worked with
  - What your goals are
  - Leadership
  - More specifics on what research you've done and how it relates to their company
  - Cover letter should convince you are a good fit for a certain company
- Develop a website
- Make sure linkedin/facebook page is updated
**** Applications and interviews: Discussion with recent graduates
- How did you prepare for your interview process?
  - Know a bit about the general information company
  - Know about recent news
  - Always have questions
  - Prepare for behavior interview questions
- How much advice did you seek out receive from your advisor?
  - Get advice on your interview talk
- It seems like it'll be difficult connecting my work to what industry values
- It will take about a month to hear back on interviews
- Make sure they think you are fully committed to their company
- Leadership skills are important it seems. How does a PhD help with that?
- Seems like the hiring process is year long
**** Perspectives of PhD Industrial Career path: Q&A panel
- Your position will most likely be similar to that of assistant professor, where you manage people doing the technical work but you need to organize the information for the higher ups
- Don't expect to go faster if you are not pushing for your own require
- Setting goals with your manager makes it happen all the more
- Expertise is far more shared in industry
- Soft skills are very important
- Parting words
  - Leverage your strengths
  - Identify other people's strengths
  - Keep learning
  - Your success is your own responsibility

* <2016-03-07 Mon> Initial meeting with Insoo
  - No connection between presence of Au metallic and cationic Au and presence of defect sites
  - In contrast to Au, some MoO_{x} ended up on the SiO_{x} support
  - Though preparation is done at an inert atmosphere, all STEM characterization is done in the presence of oxygen
  - It is likely that MoO_{x} clusters could form at the surface
  - Their main hypothesis is that Mo populates the defect sites of Au/Pt

* <2016-03-09 Wed> CMG Group meeting - "Precipitate Modeling of \alpha in Fe-Cr Alloys" - Jia-Hong Ke
  - Radiation of nuclear materials
  - Test whether short-term radiation tests could emulate long-term radiation tests
  - Experimental evidence suggests critical differences
  -
* <2016-03-10 Thu> Seminar - "Nano-Bio interactions at the cell membrane interface" - Prof. Alfredo Alexander-Katz
  - Goal is to control function of nanomaterials in biological environments
  - Interaction between a lipid covered nanoparticle and cell membrane
  - Hypothesis: nanoparticles enter membrane via fusion
  - MD simulations show fusion does happen
  - Mediated by coupling of hydrophobic tail inside membrane "lassoing" to the hydrophobic tail nailed to the nanoparticle
  - 
* <2016-03-14 Mon> Voyles Group Meeting - "Quantitative Measurements of Single La Vacancies in bulk LaMnO3" - Jie Feng
  - 2: Six years? Seems like 8 years
  - 3: Why is Delta sep not normalized?
  - 5: Phonon simulations suggest vacancies are detectable by STEM images
  - 7: Does this mean you can only detect vacancies at this height? 
  - 9: 1% chemical control?
* <2016-03-14 Mon> Seminar "CALPHAD-based Materials Genome and its Applications to Advanced Manufacturing and Materials Design" - Wei Xiong
  - 
* <2016-03-16 Wed> CMG Group Meeting - "Elastoplastic study of incoherent semiconductor core-shell nanowires"
  - Strain can make indirect band-gap --> direct band-gap
  - Goal of talk is to relate strain with defects at an epitaxial interface
  - Very general -- 3 slides have things you're not going to talk about
  - Slide 9 - make axes the same
